openapi: 3.0.0
servers:
  - description: LinkedList API
    url: http://localhost:3000/api/v1
info:
  description: LinkedList-API
  version: 1.0.0
  title: LinkedList API

paths:
  /admin/users/register:
    post:
      tags:
        - Admin
      security:
        - bearerAuth: []
      summary: Creates a user
      description: |
        Creates a user.
      responses:
        "200":
          description: created user object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Access token is missing or invalid

  /admin/users:
    get:
      tags:
        - Admin
      security:
        - bearerAuth: []
      summary: Fetches all users of the orginisation
      responses:
        "200":
          description: an array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  /admin/jobs:
    get:
      tags:
        - Admin
      security:
        - bearerAuth: []
      summary: Fetches jobs for admin dashboard
      responses:
        "200":
          description: a School object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : "#/components/schemas/Job"

  /admin/applications/download:
    get:
      tags : 
        - Admin
      security:
        - bearerAuth: []
      summary: Fetches applicants for a job
      parameters:
        - in: query
          name: jobId
          schema:
            type: string
          required: true
          description: ID of the job
      responses:
        "200":
          description: an array of applicant objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : "#/components/schemas/Application"  

  /admin/applications:  
    get:
      tags : 
        - Admin
      security:
        - bearerAuth: []
      summary: Fetches application of a user
      parameters:
        - in: query
          name: userId
          schema:
            type: string
          required: true
          description: ID of the user
      responses:
        "200":
          description: an array of applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : "#/components/schemas/Application"
  
  /auth/login:
    post:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Authenticates a User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id : 
                  type : string
                password:
                  type: string
      responses:
        "200":
          description: a School object
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                  profile:
                    type: object
                  token:
                    type: string

  /job:
    get:
      tags:
        - Job
      security:
        - bearerAuth: []
      summary: fetches all jobs for user dashboard
      description: Fetches all Jobs for user dashboard
      responses:
        "200":
          description: An array of job objects (not including posts)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Job"
        "401":
          description: Access token is missing or invalid

  /job/create:
    post:
      tags:
        - Job
      security:
        - bearerAuth: []
      summary: creates a job object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Job"
      responses:
        "200":
          description: created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"

  /job/update:
    put:
      tags:
        - Job
      security:
        - bearerAuth: []
      summary: updates a job object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Job"
      responses:
        "200":
          description: created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Job"

  /job/delete:
    delete:
      tags:
        - Job
      security:
        - bearerAuth: []
      summary: deletes a job object 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
      responses:
        "204":
          description: a Vehicle object
        "401":
          description: Access token is missing or invalid
  
  /post:
    get:
      tags:
        - Post
      security:
        - bearerAuth: []
      summary: fetches all posts
      description: Fetches all Jobs
      responses:
        "200":
          description: An array of post objects (not including jobs)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
        "401":
          description: Access token is missing or invalid

  /post/create:
    post:
      tags:
        - Post
      security:
        - bearerAuth: []
      summary: creates a post object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /post/update:
    put:
      tags:
        - Post
      security:
        - bearerAuth: []
      summary: updates a post object
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Post"
      responses:
        "200":
          description: created object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Post"

  /post/delete:
    delete:
      tags:
        - Post
      security:
        - bearerAuth: []
      summary: deletes a post object 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId:
                  type: string
      responses:
        "401":
          description: Access token is missing or invalid



  /profile:
    get:
      security:
        - bearerAuth: []
      tags: 
        - Profile
      summary: Fetches current user profile
      responses:
        "200":
          description: a profile object
          content:
            application/json:
              schema:
                type : array
                items:
                  $ref: "#/components/schemas/Profile"                  
        "401":
          description: Access token is missing or invalid

  /profile/create:
    post:
      tags:
        - Profile
      security:
        - bearerAuth: []
      summary: creates a profile for a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Profile"                
      responses:
        "200":
          description: a user profile object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"                  
        "401":
          description: Access token is missing or invalid

  /profile/update:
    put:
      tags:
        - Profile
      security:
        - bearerAuth: []
      summary: updates a user profile
      description: updates a profile.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Profile"                
      responses:
        "200":
          description: a Vehicle object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"                  
        "401":
          description: Access token is missing or invalid
    
    
    
  /application/submit:
    post:
      tags:
        - Application
      security:
        - bearerAuth: []
      summary: submit an application
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Application"
      responses:
        "200":
          description: an application object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        "401":
          description: Access token is missing or invalid

  /application/delete:
    delete:
      tags:
        - Application
      security:
        - bearerAuth: []
      summary: deletes an application
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                applicationId:
                  type: string
                userId:
                  type: string
      responses:
        "204":
          description: deleted object
        "401":
          description: Access token is missing or invalid

  /application:
    get:
      tags:
        - Application
      security:
        - bearerAuth: []
      summary: fetches applications of a student
      responses:
        "200":
          description: an array of applications
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
        "401":
          description: Access token is missing or invalid


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    Application:
      type: object
      properties:
        applicationId:
          type: string
        jobId:
          type: string
        userId:
          type: string
        dateApplied: 
          type: string
        status:
          type: string
        
    Job:
      type: object
      properties:
        jobId:
          type: string
        company:
          type: string
        body:
          type: string
        expired: 
          type: boolean
        deadline: 
          type: string


    Post:
      type: object
      properties:
        body :
          type: string



    Profile:
      type: object
      properties:
        userId:
          type: string
        summary:
          type: string
        location:
          type: string
        dateOfBirth: 
          type: string
        gpa:
          type: number
        gender:
          type: string
        resume:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        yearOfGradutation:
          type: string
        branch: 
          type: string        

    User:
      type: object
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        password:
          type: string
        kind:
          type: string
        
